const revealObserver=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.classList.add('in-view');revealObserver.unobserve(entry.target)}})},{threshold:.12});document.querySelectorAll('.reveal').forEach((el)=>revealObserver.observe(el));

const swatches=document.querySelectorAll('.swatch');const name=document.getElementById('colourName');const hex=document.getElementById('colourHex');const dot=document.querySelector('.current-dot');swatches.forEach((swatch)=>swatch.addEventListener('click',()=>{swatches.forEach((s)=>s.classList.remove('active'));swatch.classList.add('active');name.textContent=swatch.dataset.name;hex.textContent=swatch.dataset.hex;dot.style.background=swatch.dataset.hex;document.documentElement.style.setProperty('--accent',swatch.dataset.hex)}));

const menu=document.querySelector('.menu-toggle');const nav=document.querySelector('.desktop-nav');menu.addEventListener('click',()=>{nav.classList.toggle('open');document.body.classList.toggle('menu-open')});nav.querySelectorAll('a').forEach((a)=>a.addEventListener('click',()=>{nav.classList.remove('open');document.body.classList.remove('menu-open')}));

if(window.matchMedia('(pointer:fine)').matches){document.querySelectorAll('.magnetic').forEach((el)=>{el.addEventListener('mousemove',(e)=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left-r.width/2)*.12;const y=(e.clientY-r.top-r.height/2)*.12;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener('mouseleave',()=>{el.style.transform=''})})}

const form=document.getElementById('quoteForm');const note=document.getElementById('formNote');form.addEventListener('submit',(e)=>{e.preventDefault();const data=new FormData(form);const message=`Hello Spectrum Paint, I would like a quote.\nName: ${data.get('name')}\nPhone: ${data.get('phone')}\nProject: ${data.get('project')}\nNeed: ${data.get('need')||'Please advise.'}`;note.textContent='Your enquiry is ready. Opening WhatsApp…';window.open(`https://wa.me/?text=${encodeURIComponent(message)}`,'_blank');});

window.addEventListener('scroll',()=>{const header=document.querySelector('.site-header');header.classList.toggle('scrolled',window.scrollY>30)});
